# Generated by Django 3.0.9 on 2021-03-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phoneno',
            field=models.CharField(max_length=10),
        ),
    ]
