# Generated by Django 3.0.9 on 2021-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_auto_20210308_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='userid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='pizzamodel',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
