# Generated by Django 3.0.9 on 2021-03-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0006_auto_20210308_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='orderitems',
            new_name='ordereditems',
        ),
    ]
